playbooks/roles/kalite/data/kalite/control_panel/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('control_panel.views',
    # Zone
    url(r'zone/(?P<zone_id>\w+)/$', 'zone_management', {}, 'zone_management'),
    url(r'zone/(?P<zone_id>\w+)/edit$', 'zone_form', {}, 'zone_form'),

    # Device
    url(r'zone/(?P<zone_id>\w+)/device/(?P<device_id>\w+)/$', 'device_management', {}, 'device_management'),

    # Facility
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/edit$', 'facility_form', {}, 'facility_form'),
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/usage/$', 'facility_usage', {}, 'facility_usage'),
#    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/users/manage/$', 'facility_user_management', {}, 'facility_user_management'),

    url(r'account/$', 'account_management', {}, 'account_management'),

    # Group
    url(r'zone/(?P<zone_id>\w+)/facility/(?P<facility_id>\w+)/group/(?P<group_id>\w+)/users/manage/$', 'facility_user_management', {}, 'facility_user_management'),
)

playbooks/roles/kalite/data/kalite/facility/urls.py
from django.conf.urls.defaults import include, patterns, url

from . import api_urls


urlpatterns = patterns('facility.views',
    url(r'^add/teacher/$', 'add_facility_teacher', {},'add_facility_teacher'),
    url(r'^add/student/$', 'add_facility_student', {}, 'add_facility_student'),
    url(r'^edit/(?P<id>\w+)/$', 'edit_facility_user', {}, 'edit_facility_user'),

    url(r'^facility/$', 'facility_admin', {}, 'facility_admin'),
    url(r'^facility/new/$', 'facility_edit', {"id": "new"}, 'add_facility'),
    url(r'^facility/(?P<id>\w+)/$', 'facility_edit', {}, 'facility_edit'),

    url(r'^addgroup/$', 'add_group', {}, 'add_group'),
    url(r'^userlist/$', 'user_list', {}, 'user_list'),

    url(r'^login/$', 'login', {}, 'login'),
    url(r'^logout/$', 'logout', {}, 'logout'),
    url(r'^api/', include(api_urls)),
)

playbooks/roles/kalite/data/kalite/faq/urls.py
from __future__ import absolute_import

from django.conf.urls.defaults import *
from . import views as faq_views

urlpatterns = patterns('',
    url(regex = r'^$',
        view  = faq_views.TopicList.as_view(),
        name  = 'faq_topic_list',
    ),
    url(regex = r'^submit/$',
        view  = faq_views.SubmitFAQ.as_view(),
        name  = 'faq_submit',
    ),
    url(regex = r'^submit/thanks/$',
        view  = faq_views.SubmitFAQThanks.as_view(),
        name  = 'faq_submit_thanks',
    ),
    url(regex = r'^(?P<slug>[\w-]+)/$',
        view  = faq_views.TopicDetail.as_view(),
        name  = 'faq_topic_detail',
    ),
    url(regex = r'^(?P<topic_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
        view  = faq_views.QuestionDetail.as_view(),
        name  = 'faq_question_detail',
    ),
)

playbooks/roles/kalite/data/kalite/facility/models.py
from __future__ import absolute_import

import datetime
import uuid
import zlib
from annoying.functions import get_object_or_None
from pbkdf2 import crypt

from django.conf import settings
from django.contrib.auth.models import check_password
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Q
from django.utils.text import compress_string
from django.utils.translation import ugettext_lazy as _

import kalite
import settings
from config.models import Settings
from securesync import engine
from securesync.engine.models import DeferredCountSyncedModel
from settings import LOG as logging
from utils.django_utils import verify_raw_password


class Facility(DeferredCountSyncedModel):
    name = models.CharField(verbose_name=_("Name"), help_text=_("(This is the name that students/teachers will see when choosing their facility; it can be in the local language.)"), max_length=100)
    description = models.TextField(blank=True, verbose_name=_("Description"))
    address = models.CharField(verbose_name=_("Address"), help_text=_("(Please provide as detailed an address as possible.)"), max_length=400, blank=True)
    address_normalized = models.CharField(max_length=400, blank=True)
    latitude = models.FloatField(blank=True, verbose_name=_("Latitude"), null=True)
    longitude = models.FloatField(blank=True, verbose_name=_("Longitude"), null=True)
    zoom = models.FloatField(blank=True, verbose_name=_("Zoom"), null=True)
    contact_name = models.CharField(verbose_name=_("Contact Name"), help_text=_("(Who should we contact with any questions about this facility?)"), max_length=60, blank=True)
    contact_phone = models.CharField(max_length=60, verbose_name=_("Contact Phone"), blank=True)
    contact_email = models.EmailField(max_length=60, verbose_name=_("Contact Email"), blank=True)
    user_count = models.IntegerField(verbose_name=_("User Count"), help_text=_("(How many potential users do you estimate there are at this facility?)"), blank=True, null=True)

    class Meta:
        verbose_name_plural = "Facilities"
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        if not self.id:
            return self.name
        return u"%s (#%s)" % (self.name, int(self.id[:3], 16))

    def is_default(self):
        return self.id == Settings.get("default_facility")

    @classmethod
    def from_zone(cls, zone):
        """Our best approximation of how to map facilities to zones"""

        facilities = set(Facility.objects.filter(zone_fallback=zone))

        for device_zone in DeviceZone.objects.filter(zone=zone):
            device = device_zone.device
            facilities = facilities.union(set(Facility.objects.filter(signed_by=device)))

        return facilities


class FacilityGroup(DeferredCountSyncedModel):
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    name = models.CharField(max_length=30, verbose_name=_("Name"))

    class Meta:
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return self.name


class FacilityUser(DeferredCountSyncedModel):
    # Translators: This is a label in a form.
    facility = models.ForeignKey(Facility, verbose_name=_("Facility"))
    # Translators: This is a label in a form.
    group = models.ForeignKey(FacilityGroup, verbose_name=_("(Group/class)"), blank=True, null=True, help_text=_("(optional)"))
    # Translators: This is a label in a form.
    username = models.CharField(max_length=30, verbose_name=_("Username"))
    # Translators: This is a label in a form.
    first_name = models.CharField(max_length=30, verbose_name=_("First Name"), blank=True)
    # Translators: This is a label in a form.
    last_name = models.CharField(max_length=60, verbose_name=_("Last Name"), blank=True)
    # Translators: This is a label in a form.
    is_teacher = models.BooleanField(default=False, help_text=_("(whether this user should have teacher permissions)"))
    notes = models.TextField(blank=True)
    password = models.CharField(max_length=128)
    default_language = models.CharField(max_length=8, blank=True, null=True); default_language.minversion="0.11.1"

    class Meta:
        unique_together = ("facility", "username")
        app_label = "securesync"  # for back-compat reasons

    def __unicode__(self):
        return u"%s (Facility: %s)" % (self.get_name(), self.facility)

    def save(self, *args, **kwargs):
        """
        Validate password format before saving
        """
        # Now, validate password.
        if self.password.split("$", 1)[0] == "sha1":
            # Django's built-in password checker for SHA1-hashed passwords
            pass

        elif len(self.password.split("$", 2)) == 3 and self.password.split("$", 2)[1] == "p5k2":
            # PBKDF2 password checking
            # Could fail if password doesn't split into parts nicely
            pass

        elif self.password:
            raise ValidationError(_("Unknown password format."))

        super(FacilityUser, self).save(*args, **kwargs)

        # in case the password was changed on another server, and then synced into here, clear cached password
        CachedPassword.invalidate_cached_password(user=self)

    def check_password(self, raw_password):
        cached_password = CachedPassword.get_cached_password(self)
        cur_password = cached_password or self.password

        # Check the password
        if cur_password.split("$", 1)[0] == "sha1":
            # use Django's built-in password checker for SHA1-hashed passwords
            okie_dokie = check_password(raw_password, cur_password)
        elif cur_password.split("$", 2)[1] == "p5k2":
            # use PBKDF2 password checking
            okie_dokie = cur_password == crypt(raw_password, cur_password)
        else:
            raise ValidationError(_("Unknown password format."))

        # Update on cached password-relevant stuff
        if okie_dokie and not cached_password and self.id:  # only can create if the user's been saved
            CachedPassword.set_cached_password(self, raw_password=raw_password)

        return okie_dokie

    def set_password(self, raw_password=None, hashed_password=None, cached_password=None):
        """Set a password with the raw password string, or the pre-hashed password.
        If using the raw string, """
        assert hashed_password is None or settings.DEBUG, "Only use hashed_password in debug mode."
        assert raw_password is not None or hashed_password is not None, "Must be passing in raw or hashed password"
        assert not (raw_password is not None and hashed_password is not None), "Must be specifying only one--not both."

        if raw_password:
            verify_raw_password(raw_password)

        if hashed_password:
            self.password = hashed_password

            # Can't save a cached password from a hash, so just make sure there is none.
            # Note: Need to do this, even if they're not enabled--we don't want to risk
            #   being out of sync (if people turn on/off/on the feature
            CachedPassword.invalidate_cached_password(user=self)

        else:
            n_iters = settings.PASSWORD_ITERATIONS_TEACHER_SYNCED if self.is_teacher else settings.PASSWORD_ITERATIONS_STUDENT_SYNCED
            self.password = crypt(raw_password, iterations=n_iters)

            if self.id:
                CachedPassword.set_cached_password(self, raw_password)

    def get_name(self):
        if self.first_name and self.last_name:
            return u"%s %s" % (self.first_name, self.last_name)
        else:
            return self.username


class CachedPassword(models.Model):
    """
    Local store of password hashes, using a locally settable # of password hash iterations.
    """
    user = models.ForeignKey("FacilityUser", unique=True)
    password = models.CharField(max_length=128)

    @classmethod
    def is_enabled(cls):
        # 0 is an illegal value, so 0 or None means disabled
        # Force both to be set; otherwise, assumptions below can break
        return bool(settings.PASSWORD_ITERATIONS_TEACHER and settings.PASSWORD_ITERATIONS_STUDENT)

    @classmethod
    def iters_for_user_type(cls, user):
        return settings.PASSWORD_ITERATIONS_TEACHER if user.is_teacher else settings.PASSWORD_ITERATIONS_STUDENT

    @classmethod
    def get_cached_password(cls, user):
        if not cls.is_enabled():
            return None

        # Cache miss because there is no row in the table for this user.
        cached_password = cls.is_enabled() and get_object_or_None(cls, user=user)
        if not cached_password:
            logging.debug("Cached password MISS (does not exist) for user=%s" % user.username)
            return None

        n_cached_iters = int(cached_password.password.split("$")[2], 16)  # this was determined
        if n_cached_iters == cls.iters_for_user_type(user):
            # Cache hit!
            logging.debug("Cached password hit for user=%s; cached iters=%d" % (user.username, n_cached_iters))
            return cached_password.password
        else:
            # Cache miss because the row is invalid (# hashes doesn't match the current cache setting)
            logging.debug("Cached password MISS (invalid) for user=%s" % user.username)
            cached_password.delete()
            return None

    @classmethod
    def invalidate_cached_password(cls, user):
        cls.objects.filter(user=user).delete()

    @classmethod
    def set_cached_password(cls, user, raw_password):
        assert user.id, "Your user must have an ID before calling this function."

        if not cls.is_enabled():
            # Must delete, to make sure we don't get out of sync.
            cls.invalidate_cached_password(user=user)

        else:
            try:
                # Set the cached password.

playbooks/roles/kalite/data/kalite/control_panel/forms.py
from django import forms
from django.forms import ModelForm

from securesync.models import Zone


class ZoneForm(ModelForm):
    class Meta:
        model = Zone
        fields = ('name', 'description')

class UploadFileForm(forms.Form):
    file  = forms.FileField()

class DateRangeForm(forms.Form):
    """Form that validates Dates for CSV Export"""

    period_start = forms.DateField()
    period_end = forms.DateField()

playbooks/roles/kalite/data/kalite/templates/control_panel/account_management.html
{% extends "control_panel/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load my_filters %}
{% load include_block %}

{% block control_panel_active %}{% endblock control_panel_active %}
{% block account_management_active %}active{% endblock account_management_active %}

{% block title %}{{ student.get_name }} - {% trans "User Management" %}{{ block.super }}{% endblock title%}

{% block headcss %}{% comment %}Don't insert block.super here, because block.super is WEIRD and isn't the super for student_view IN student view, but instead THIS super.{% endcomment %}
    {% include_block "coachreports/student_view.html" "headcss" %}
{% endblock headcss %}


{% block titlebar_title %}
    <li>
        {% blocktrans with student_name=student.get_name %}Account management page for {{ student_name }}{% endblocktrans %}
    </li>
{% endblock titlebar_title %}

{% block buttons %}
    {% if not is_central %}
        {% if not restricted %}
        <li>
            <a class="green_button" href="{% url edit_facility_user id=student.id %}?next={{ request.path }}">{% trans "Change password" %}</a>
        </li>
        {% endif %}
        <li class="client-online-only">
            <a class="server-online-only green_button" href="{% url update_all_distributed %}">{% trans "Download data from Khan Academy" %}</a>
        </li>
    {% endif %}
{% endblock buttons %}

{% block content %}
    {% block titlebar %}{{ block.super }}
    {% endblock titlebar %}

    {% include_block "coachreports/student_view.html" "student_report" %}
{% endblock content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/base.html
{% extends base_template %}
{% load staticfiles %}
{% load i18n %}

{% block control_panel_active %}active{% endblock control_panel_active %}

{% block headcss %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/control_panel/base.css' %}" />
{% endblock headcss %}

{% block content %}
    {% block titlebar %}
        <div class="titlebar">
            <ul class="titlebar__title">
            {% block titlebar_title %}
                {% comment "Draw the top navigation bar %}{% endcomment %}
                {% if org %}
                <li><a href="{% url org_management %}"> {{ org.name }}</a></li>
                {% endif %}

                <li>
                    {% if org %}&gt;{% endif %}
                    {% if facility or device %}<a href="{%url zone_management org_id=org_id zone_id=zone_id %}">{% endif %}
                        {% if zone %}
                            {{ zone.name }}
                        {% elif not zone %}
                            {% if is_central %}
                            {% trans "New Sharing Network" %}
                            {% else %}
                            Unregistered Device {{ device.name }} - <a class="not-registered-only" href="{% url register_public_key %}">Register Now!</a>
                            {% endif %}
                        {% endif %}
                    {% if facility or device %}</a>
                    {% elif own_device_is_trusted %} <a class="edit-link" href="{% url zone_form org_id=org_id zone_id=zone_id %}">(edit)</a>
                    {% endif %}
                </li>
                <li>

                {% if device %}
                <li>&gt; {% if device.name %}{{ device.name }}{% else %}{{ device.id }}{% endif %}</li>
                {% endif %}

                {% if facility %}
                <li>
                    &gt; {{ facility.name }}
                    {% if not group %}
                    <a class="edit-link" href="{% url facility_form org_id=org_id zone_id=zone_id facility_id=facility.id %}">(edit)</a>
                    {% endif %}
                </li>
                {% endif %}

                {% if group %}
                <li>{% if facility %}&gt; {% endif %}{{ group.name }}</li>

                {% endif %}
            {% endblock titlebar_title %}
                {% comment "Provide upload/download buttons; each button should be an LI" %}{% endcomment %}
                {% comment "Provide upload/download buttons; each button should be an LI" %}{% endcomment %}
                <ul class="titlebar__buttons">
                {% block buttons %}
                {% endblock buttons %}
                </ul>
            </ul>
        </div>
    {% endblock titlebar %}

    {% block control_panel_content %}
    {% endblock control_panel_content %}
{% endblock content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/base_printable.html
{% extends "control_panel/base.html" %}
{% load i18n %}

{% block buttons %}{{ block.super }}
    <!--li>
        <a class="green_button" href="javascript:alert('NYI; sorry!');">{% trans "Print Report" %}</a>
    </li-->
{% endblock buttons %}

playbooks/roles/kalite/data/kalite/templates/control_panel/device_management.html
{% extends "control_panel/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{{ device.name }}{% trans "Device Syncing History" %}{{ block.super }}{% endblock title %}

{% block headcss %}{{ block.super }}
    <style>
        dl{margin-bottom:20px}dt,dd{line-height:20px}dt{font-weight:bold}dd{margin-left:10px}.dl-horizontal{*zoom:1}.dl-horizontal:before,.dl-horizontal:after{display:table;line-height:0;content:""}.dl-horizontal:after{clear:both}.dl-horizontal dt{float:left;width:160px;overflow:hidden;clear:left;text-align:right;text-overflow:ellipsis;white-space:nowrap}.dl-horizontal dd{margin-left:180px}
    </style>
{% endblock headcss %}

{% block buttons %}{{ block.super }}
    {% if is_own_device %}
        <div class="server-online-only">
            <a class="registered-only green_button" href="javascript:force_sync()">{% trans "Sync Now!" %}</a>
            <a class="not-registered-only green_button" href="{% url register_public_key %}">{% trans "Register" %}</a>
        </div>
    {% endif %}
{% endblock buttons %}

{% block control_panel_content %}
    <div id="zone_container">

        <div class="device_metadata">
            <h2>{% trans "Device Metadata" %}</h2>

            <dl class="dl-horizontal">
            {% if software_version %}
                <!---Current System status -->
                <dt>{% trans "Device ID" %}:</dt>
                <dd>{{ device.id }}</dd>
                <dt>{% trans "Current Version" %}:</dt>
                <dd>{{ software_version }}</dd>
                <dt>{% trans "Released Date" %}:</dt>
                <dd>{{ software_release_date }}</dd>
                <dt>{% trans "Database Size" %}:</dt>
                <dd>{{ database_size|floatformat }} MB</dd>
                <dt>{% trans "Database last update" %}:</dt>
                <dd>{{ database_last_updated }}</dd>
                <dt>{% trans "Install Directory" %}:</dt>
                <dd>{{ install_dir }}</dd>

            {% elif not shown_sessions %}

            {% else %}
                <!---Remote system status -->
                <dt>{% trans "Version" %}:</dt>
                <dd>{{ shown_sessions.0.client_version }}</dd>
                <dt>{% trans "Operating System" %}:</dt>
                <dd>{{ shown_sessions.0.client_os }}</dd>
            {% endif %}
            </dl>
        </div>

        <div class="sync_sessions">
            <div>
                <h2>{% trans "Sync Sessions" %}</h2>
            </div>

            {% if not shown_sessions %}
                <p class="registered-only">{% trans "This device has never synced with the central server." %}</p>
                <p class="not-registered-only">{% trans "This device is not registered, and so cannot sync data with the central server." %}</p>
            {% else %}
                {% with shown_sessions|length as shown_count %}
                {# Translators: shown_count and total_sessions are integer variables; do not translate them! #}
                <span>({% blocktrans %}showing {{ shown_count }} of {{ total_sessions }}{% endblocktrans %})</span>
                {% endwith %}
                <table class="simple-table">
                    <tr>
                        <th width="250px">{% trans "Sync Date" %}</th>
                        <th width="250px">{% trans "Device IP Address" %}</th>
                        <th width="200px">{% trans "# Models Uploaded" %}</th>
                        <th width="200px">{% trans "# Models Downloaded" %}</th>
                        <th width="200px">{% trans "# Errors" %}</th>
                    </tr>
                    {% for sync_session in shown_sessions %}
                        <tr>
                            <td>{{ sync_session.timestamp }}</td>
                            <td>{{ sync_session.ip }}</td>
                            <td>{{ sync_session.models_uploaded }}</td>
                            <td>{{ sync_session.models_downloaded }}</td>
                            <td>{{ sync_session.errors }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>

    </div><!-- zone_container -->
{% endblock control_panel_content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/facility_form.html
{% extends "control_panel/base.html" %}
{% load i18n %}

{% block title %}{% trans "Facility Add / Update" %}{{ block.super }}{% endblock title %}

{% block headcss %}
    <style>
        #map_canvas {
            display: none;
            margin-bottom: 30px;
            width: 100%;
            height: 400px
        }
        #search-panel {
            width: 550px;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            margin-bottom: 10px;
            border: 1px solid #999;
        }       
        #target {
            width: 545px;
        }

        #id_name {
            width: 300px;
        }

        #id_address {
            width: 500px;
        } 

        #id_latitude, #id_longitude {
            width: 150px;
        }

        #id_direc_map {
            display: none;
            padding-bottom: 10px;
            font-size: 14px;
        }

        #id_direc_no_map {
            padding-bottom: 10px;
            font-size: 14px;
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUVMGp6Uks8OCczFfrWo20zHnmENyW5O0&v=3.9&sensor=false&libraries=places"></script>
    <script>
        $(function() {
            $('#id_address_normalized').parent().hide();
            $('#id_zoom').parent().hide();
            $('#id_latitude').parent().hide();
            $('#id_longitude').parent().hide();
        });

        function displayFormLatLng(map, marker) {
            var longitude = $("#id_longitude").val();
            var latitude = $("#id_latitude").val();
            if (longitude && latitude) {
                var latLng = new google.maps.LatLng(latitude, longitude);
                map.setCenter(latLng);
                marker.setPosition(latLng);
                marker.setVisible(true);
            }
        }
   
        function initialize()
        {
            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                mapTypeId: google.maps.MapTypeId.SATELLITE,
                scrollwheel: false,
                maxZoom: 20,
                minZoom: 3,
            });
            var defaultBounds = new google.maps.LatLngBounds(
                new google.maps.LatLng(-33.8902, 151.1759),
                new google.maps.LatLng(-33.8474, 151.2631));
            map.fitBounds(defaultBounds);

            var input = document.getElementById('target');
            var searchBox = new google.maps.places.Autocomplete(input);
    
            var myLatLng = new google.maps.LatLng(-33.8902, 151.1759);

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                draggable: true,
                visible: false,
                clickable: true,
            });

            saveZoom(map.getZoom());

            google.maps.event.addListener(map, 'click', function(ev) {
                    marker.setVisible(true);
                    marker.setPosition(ev.latLng);
                    saveLatLng(ev.latLng.lat(), ev.latLng.lng());
            });


            google.maps.event.addListener(searchBox, 'place_changed', function() {
                var place = searchBox.getPlace();
                var bounds = new google.maps.LatLngBounds();

                marker.setVisible(true);
                marker.setPosition(place.geometry.location);
                bounds.extend(place.geometry.location);
                saveLatLng(place.geometry.location.lat(), place.geometry.location.lng());
                getAddress(place.formatted_address);
                // if a place has a geometry, display it on the map
                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);   
                    marker.setPosition(place.geometry.viewport);
                } 
                else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(13);
                }
            });

            $('#map_canvas').show();
            $('#id_direc_no_map').hide();
            $('#id_direc_map').show();
            google.maps.event.addListenerOnce(map, 'idle', function() {
                displayFormLatLng(map, marker);
            });

            google.maps.event.addListener(map, 'zoom_changed', function(){
                saveZoom(map.getZoom());
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);

        function saveLatLng(lat, lon) {
            $("#id_latitude").val(lat);
            $("#id_longitude").val(lon);
        }

        function getAddress(ad) {
            $("#id_address_normalized").val(ad);
        }

        function saveZoom(zm) {
            $("#id_zoom").val(zm);
        }
    </script>
{% endblock headjs %}

{% block control_panel_content %}
    <h2>
        {% if form.instance.id %}{% trans "Edit a facility" %}{% else %}{% trans "Add a new Facility" %}{% endif %}
    </h2>
    <div id="id_direc_no_map">
        {% trans "Please enter the following information about your facility. Please enter a detailed address, because knowing where you are in the world allows us to better plan for future deployments and partnerships." %}
    </div>
    <div id="id_direc_map">
        {% trans "Please use this search box to locate your facility (and/or click on the map to select a spot), and then enter the additional information in the form below." %}<br/>
        {% trans "(Knowing, as closely as possible, where you are in the world allows us to better plan for future deployments and partnerships)" %}
    </div>
    <div id="search-panel">
        {% trans "Search for your facility's address or name to find its location on the map (enter to search)" as placeholder %}
        <input id="target" type="text" placeholder="{{placeholder}}">
    </div>
    <div id="map_canvas"></div>
    <form id="facility_form" method="post" class="basic-form">
        {% csrf_token %}
        {{ form.as_p }}
        {% trans "Save facility" as value %}
        <input type="submit" value="{{ value }}" class="submit"/>
    </form>
{% endblock control_panel_content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/group_report.html
{% extends "control_panel/base_printable.html" %}
{% load i18n %}
{% load staticfiles %}
{% load include_block %}

{% block title %}{{ group.name }} - {% trans "Group Report" %}{{ block.super }}{% endblock title %}

{% block headjs %}{{ block.super }}
    {% include_block "coachreports/tabular_view.html" "headjs" %}
{% endblock headjs %}

{% block headcss %}{{ block.super }}
    {% include_block "coachreports/tabular_view.html" "headcss" %}
{% endblock headcss %}

{% block control_panel_content %}
    <div id="group_container">
        {% include_block "coachreports/tabular_view.html" "content" %}
    </div>
{% endblock control_panel_content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/group_users_management.html
{% extends "control_panel/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load include_block %}

{% block title %}{{ group.name }} - {% trans "User Management" %}{{ block.super }}{% endblock title %}

{% block headcss %}{{ block.super }}
    {% include_block "facility/current_users.html" "headcss" %}
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    {% include_block "facility/current_users.html" "headjs" %}
{% endblock headjs %}

{% block control_panel_content %}
    <div id="content">
        {% include_block "facility/current_users.html" "users_table" %}
    </div>
{% endblock control_panel_content %}

playbooks/roles/kalite/data/kalite/templates/control_panel/zone_form.html
{% extends "control_panel/base.html" %}
{% load i18n %}

{% block title %}{{ zone.name }} - {% trans "Sharing Network Add / Edit" %} {{ block.super }}{% endblock title %}

{% block control_panel_content %}
<div id="zone_container">
    <form method="post" class="basic-form">
    {% csrf_token %}

    <div>
        <h2>
            {% if form.instance.pk %}{% trans "Update Your Sharing Network" %}{% else %}{% trans "Create A Sharing Network" %}{% endif %}
            <span class="glossary-link nudge-left" title="{% trans "A 'Sharing Network' is a set of KA Lite installations that share logins and student progress with each other through the internet (when available)." %}"></span>
        </h2>

        {{ form.as_p }}

        {% if form.instance.pk %}
        <input type="submit" value="{% trans 'Update Sharing Network' %}" class="button"/>
        {% else %}
        <input type="submit" value="{% trans 'Create Sharing Network' %}" class="button"/>
        {% endif %}
    </div>
    </form>
</div>
{% endblock control_panel_content %}